import React from "react";
export const metadata = {
  title: "Dashboard||Sewing",
  description: "Generated by create next app",
};

const Dashboardlayout = ({ children }) => {
  return (
    <div>
      <h1>Sidebar</h1>
      {children}
    </div>
  );
};

export default Dashboardlayout;
